#!/opt/conda/bin/python
from collections import Counter
from multiprocessing import Process
from tqdm import tqdm
import os

os.chdir('/workspace/MSWC')
with open('languages') as f:
    languages = [line.strip() for line in f]

def frequent(lang, split, FILE):
    idx = 2 if split == 'all' else 1
    if split == 'all': split = 'splits'

    csv_file = f'splits/{lang}/{lang}_{split}.csv'
    with open(csv_file) as f:
        f.readline()
        words = [line.split(',')[idx] for line in f]
    
    files_count = Counter(words).most_common()
    with open(FILE, 'w') as f:
        for word, count in files_count:
            print(f"{count:<10}{word}", file=f)

splits = ['all', 'train', 'dev', 'test']
for split in splits:
    subdir = f'frequent/{split}'
    if not os.path.isdir(subdir):
        os.makedirs(subdir)

    ps = []
    for lang in languages:
        FILE = f'{subdir}/{lang}.frequent'
        p = Process(target=frequent, args=(lang, split, FILE))
        p.start()
        ps.append(p)

    for p in tqdm(ps, desc=split): p.join()
