#!/bin/bash
[ -z $1 ] && { echo "usage: ${0##*/} DATASET_HOME"; exit 1; }
cd $1 &> /dev/null || { echo "failed cd to $1"; exit 1; }

outfile='.audio.index.txt'
find * -maxdepth 1 -name '*.wav' | tqdm > $outfile

